export const GET_OPERATIONS = "GET_OPERATIONS";
export const GET_BALANCE = "GET_BALANCE";
export const GET_FINAL_INCOME = "GET_FINAL_INCOME";
export const GET_FINAL_EXPENDITURE = "GET_FINAL_EXPENDITURE"
export const POST_OPERATION = "POST_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";
export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const GET_ID_OPERATION = "GET_ID_OPERATION";
export const ORDER_BY_DATE = "ORDER_BY_DATE";
//
export const GET_USERS = "GET_USERS";
export const POST_USER = "POST_USER";
export const GET_EMAIL_USER = "GET_EMAIL_USER";
